---
- name: 2.2.1 Ensure ftp client is not installed
  ansible.builtin.dnf:
    name: ftp
    state: absent
  tags:
    - clients
    - dnf

- name: 2.2.2 Ensure ldap client is not installed
  ansible.builtin.dnf:
    name: openldap-clients
    state: absent
  tags:
    - clients
    - dnf

- name: 2.2.3 Ensure nis client is not installed
  ansible.builtin.dnf:
    name: ypbind
    state: absent
  tags:
    - clients
    - dnf

- name: 2.2.4 Ensure telnet client is not installed
  ansible.builtin.dnf:
    name: telnet
    state: absent
  tags:
    - clients
    - dnf

- name: 2.2.5 Ensure tftp client is not installed
  ansible.builtin.dnf:
    name: tftp
    state: absent
  tags:
    - clients
    - dnf
